export const HOST_DOCUMENT_TYPES = {
  CONTRACT: 'CONTRACT',
  PRIVACY_CONSENT: 'PRIVACY_CONSENT',
  BUSINESS_CERTIFICATE: 'BUSINESS_CERTIFICATE',
};

export const HOST_DOCUMENT_LABELS = {
  [HOST_DOCUMENT_TYPES.CONTRACT]: '계약서',
  [HOST_DOCUMENT_TYPES.PRIVACY_CONSENT]: '개인정보 동의서',
  [HOST_DOCUMENT_TYPES.BUSINESS_CERTIFICATE]: '사업자등록증',
};
