export const HOST_DOCUMENT_TYPES = {
  CONTRACT: 'CONTRACT',
  PRIVACY_CONSENT: 'PRIVACY_CONSENT',
  BUSINESS_CERTIFICATE: 'BUSINESS_CERTIFICATE',
  BANKBOOK_COPY: 'BANKBOOK_COPY',
  BUSINESS_REPORT_CERTIFICATE: 'BUSINESS_REPORT_CERTIFICATE',
};

export const HOST_DOCUMENT_LABELS = {
  [HOST_DOCUMENT_TYPES.CONTRACT]: '계약서',
  [HOST_DOCUMENT_TYPES.PRIVACY_CONSENT]: '개인정보 동의서',
  [HOST_DOCUMENT_TYPES.BUSINESS_CERTIFICATE]: '사업자등록증',
  [HOST_DOCUMENT_TYPES.BANKBOOK_COPY]: '통장 사본',
  [HOST_DOCUMENT_TYPES.BUSINESS_REPORT_CERTIFICATE]: '영업 신고증',
};
